//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBusinessLogicalLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloodBusinessLogicalLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی اطلاعات امکان پذیز نمی باشد!.
        /// </summary>
        internal static string errGetBlood {
            get {
                return ResourceManager.GetString("errGetBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خون مورد نظر از سامانه حذف گردید!.
        /// </summary>
        internal static string stringDeletBlood {
            get {
                return ResourceManager.GetString("stringDeletBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ویرایش گردید!.
        /// </summary>
        internal static string stringEditBlood {
            get {
                return ResourceManager.GetString("stringEditBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خون مورد نظر در سامانه موجود می باشد!.
        /// </summary>
        internal static string stringFoundBlood {
            get {
                return ResourceManager.GetString("stringFoundBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خون مورد نظر در سامانه موجود نمی باشد!.
        /// </summary>
        internal static string stringNotFoundBlood {
            get {
                return ResourceManager.GetString("stringNotFoundBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات در سامانه ذخیره گردید!.
        /// </summary>
        internal static string stringSaveBlood {
            get {
                return ResourceManager.GetString("stringSaveBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات گروه خونی را وارد نمایید!.
        /// </summary>
        internal static string validationBloodGroup {
            get {
                return ResourceManager.GetString("validationBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات سریال خون را وارد نمایید!.
        /// </summary>
        internal static string validationBloodSerial {
            get {
                return ResourceManager.GetString("validationBloodSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت را وارد نمایید!.
        /// </summary>
        internal static string validationRegisterDate {
            get {
                return ResourceManager.GetString("validationRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش مربوطه را وارد نمایید!.
        /// </summary>
        internal static string validationSection {
            get {
                return ResourceManager.GetString("validationSection", resourceCulture);
            }
        }
    }
}
